import type { Address } from '@/types/booking'

export const mockAddresses: Address[] = [
  {
    id: 'addr-1',
    client_id: 'user-1',
    type: 'home',
    label: 'Domicile',
    street: '15 Rue de la Paix',
    city: 'Paris',
    postal_code: '75002',
    country: 'France',
    is_default: true,
    latitude: 48.8698,
    longitude: 2.3315,
    created_at: new Date().toISOString(),
  },
  {
    id: 'addr-2',
    client_id: 'user-1',
    type: 'work',
    label: 'Bureau',
    street: '42 Avenue des Champs-Élysées',
    city: 'Paris',
    postal_code: '75008',
    country: 'France',
    is_default: false,
    latitude: 48.8707,
    longitude: 2.3072,
    created_at: new Date().toISOString(),
  },
  {
    id: 'addr-3',
    client_id: 'user-1',
    type: 'other',
    label: 'Chez mes parents',
    street: '8 Boulevard Saint-Michel',
    city: 'Paris',
    postal_code: '75005',
    country: 'France',
    is_default: false,
    latitude: 48.8527,
    longitude: 2.3425,
    created_at: new Date().toISOString(),
  },
]
