import type { Service, ServiceCategory } from '@/types/booking'

export const mockCategories: ServiceCategory[] = [
  { id: '1', name: 'Coiffure', slug: 'coiffure' },
  { id: '2', name: 'Beauté des ongles', slug: 'beaute-ongles' },
  { id: '3', name: 'Soins du visage', slug: 'visage' },
  { id: '4', name: 'Massage bien-être', slug: 'massage' },
  { id: '5', name: 'Minceur & drainage', slug: 'minceur' },
]

export const mockServices: Service[] = [
  {
    id: 'coiffure-1',
    name: 'Coupe Femme',
    category: 'coiffure',
    description: 'Coupe de cheveux professionnelle adaptée à votre style. Inclut shampoing et brushing.',
    duration: 60,
    price: 55,
    image_url: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80',
    is_active: true,
  },
  {
    id: 'coiffure-2',
    name: 'Coloration + Coupe',
    category: 'coiffure',
    description: 'Coloration complète avec coupe, shampoing et brushing. Produits professionnels.',
    duration: 180,
    price: 120,
    image_url: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80',
    is_active: true,
  },
  {
    id: 'ongles-1',
    name: 'Manucure Classique',
    category: 'beaute-ongles',
    description: 'Soin complet des mains avec pose de vernis. Lime, cuticules, massage.',
    duration: 45,
    price: 35,
    image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80',
    is_active: true,
  },
  {
    id: 'ongles-2',
    name: 'Pose Gel UV',
    category: 'beaute-ongles',
    description: 'Pose de vernis semi-permanent UV longue tenue (3-4 semaines). Inclut manucure.',
    duration: 90,
    price: 60,
    image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80',
    is_active: true,
  },
  {
    id: 'visage-1',
    name: 'Soin du Visage Hydratant',
    category: 'visage',
    description: 'Soin complet : nettoyage, gommage, masque hydratant et massage du visage.',
    duration: 60,
    price: 70,
    image_url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    is_active: true,
  },
  {
    id: 'visage-2',
    name: 'Soin Anti-Âge Premium',
    category: 'visage',
    description: 'Soin ciblé anti-âge avec sérum, massage kobido et masque lifting.',
    duration: 90,
    price: 95,
    image_url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    is_active: true,
  },
  {
    id: 'massage-1',
    name: 'Massage Suédois 60min',
    category: 'massage',
    description: 'Massage relaxant du corps entier. Huiles essentielles au choix.',
    duration: 60,
    price: 80,
    image_url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    is_active: true,
  },
  {
    id: 'massage-2',
    name: 'Massage Californien 90min',
    category: 'massage',
    description: 'Massage enveloppant et profond pour une détente maximale. Musique douce incluse.',
    duration: 90,
    price: 110,
    image_url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    is_active: true,
  },
  {
    id: 'massage-3',
    name: 'Massage Dos & Nuque',
    category: 'massage',
    description: 'Massage ciblé pour soulager tensions et douleurs dorsales. Idéal bureau.',
    duration: 30,
    price: 45,
    image_url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    is_active: true,
  },
  {
    id: 'minceur-1',
    name: 'Drainage Lymphatique',
    category: 'minceur',
    description: 'Drainage manuel pour éliminer toxines et réduire rétention d\'eau.',
    duration: 60,
    price: 75,
    image_url: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80',
    is_active: true,
  },
]
