openapi: 3.1.0
info:
  title: Service Zones API
  description: API for validating addresses are within service coverage zones
  version: 1.0.0

servers:
  - url: https://your-project.supabase.co/functions/v1
    description: Supabase Edge Functions

paths:
  /validate-service-zone:
    post:
      summary: Validate address is in service zone
      description: |
        Checks if given coordinates fall within active service zones.
        - Uses PostGIS for geospatial point-in-polygon check
        - Returns zone name if valid
        - Suggests alternative zones if out of coverage
        - Optionally stores request for future expansion tracking
      operationId: validateServiceZone
      tags:
        - Service Zones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceZoneValidationRequest'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceZoneValidationResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /get-service-zones:
    get:
      summary: Get all active service zones
      description: Returns list of all active service zones with boundaries
      operationId: getServiceZones
      tags:
        - Service Zones
      responses:
        '200':
          description: List of service zones
          content:
            application/json:
              schema:
                type: object
                required:
                  - zones
                properties:
                  zones:
                    type: array
                    items:
                      $ref: '#/components/schemas/ServiceZone'

  /request-zone-expansion:
    post:
      summary: Request service in new area
      description: |
        Records user interest in service expansion to a new area.
        - Stores location data for demand analysis
        - Optionally collects email for notification
        - Helps prioritize expansion areas
      operationId: requestZoneExpansion
      tags:
        - Service Zones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - latitude
                - longitude
                - address
              properties:
                latitude:
                  type: number
                  format: float
                  example: 48.8566
                longitude:
                  type: number
                  format: float
                  example: 2.3522
                address:
                  type: string
                  example: "10 rue de la Paix, 75002 Paris"
                email:
                  type: string
                  format: email
                  description: Optional email for notification when zone becomes available
                  example: "client@example.com"
      responses:
        '201':
          description: Request recorded
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Nous vous notifierons lorsque nous couvrirons cette zone"

components:
  schemas:
    ServiceZoneValidationRequest:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          format: float
          description: Latitude of service address
          example: 48.8606
        longitude:
          type: number
          format: float
          description: Longitude of service address
          example: 2.3376
        address:
          type: string
          description: Full address (for context)
          example: "15 rue de Rivoli, 75001 Paris"

    ServiceZoneValidationResponse:
      type: object
      required:
        - isValid
      properties:
        isValid:
          type: boolean
          description: Whether address is in service zone
          example: true
        zoneName:
          type: string
          description: Name of the zone (if valid)
          example: "Paris 1er"
        zoneId:
          type: integer
          format: int64
          example: 5
        message:
          type: string
          example: "Cette adresse est couverte par nos services"
        nearestZones:
          type: array
          description: Nearest zones if address is out of coverage
          items:
            type: object
            properties:
              zoneId:
                type: integer
                format: int64
                example: 6
              zoneName:
                type: string
                example: "Paris 2e"
              distanceKm:
                type: number
                format: float
                example: 1.2
        alternativeSuggestion:
          type: string
          description: Suggestion if out of zone
          example: "Nous ne couvrons pas encore cette zone. Zones proches : Paris 2e (1.2 km)"

    ServiceZone:
      type: object
      required:
        - id
        - name
        - zoneType
        - centerLat
        - centerLng
      properties:
        id:
          type: integer
          format: int64
          example: 5
        name:
          type: string
          example: "Paris 1er"
        zoneType:
          type: string
          enum: [city, arrondissement, postal_code, custom_polygon]
          example: "arrondissement"
        centerLat:
          type: number
          format: float
          example: 48.8650
        centerLng:
          type: number
          format: float
          example: 2.3357
        postalCodes:
          type: array
          items:
            type: string
          example: ["75001"]
        boundaryCoordinates:
          type: object
          description: GeoJSON polygon
          example:
            type: "Polygon"
            coordinates:
              - - [2.3285, 48.8606]
                - [2.3429, 48.8606]
                - [2.3429, 48.8702]
                - [2.3285, 48.8702]
                - [2.3285, 48.8606]

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "INVALID_COORDINATES"
        message:
          type: string
          example: "Latitude and longitude must be valid numbers"
