/**
 * Approve Contractor Application Edge Function
 * Task: T039 - Account creation, onboarding initialization, credentials email
 * Feature: 007-contractor-interface
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface ApproveApplicationRequest {
  applicationId: number
  customSlug?: string
  sendEmail?: boolean
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // Create Supabase client with service role
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false
        }
      }
    )

    // Get request body
    const { applicationId, customSlug, sendEmail = true }: ApproveApplicationRequest = await req.json()

    // Validate input
    if (!applicationId) {
      return new Response(
        JSON.stringify({ error: 'Missing application ID' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Get application details
    const { data: application, error: fetchError } = await supabaseClient
      .from('contractor_applications')
      .select('*')
      .eq('id', applicationId)
      .single()

    if (fetchError || !application) {
      return new Response(
        JSON.stringify({ error: 'Application not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Check if already approved
    if (application.status === 'approved') {
      return new Response(
        JSON.stringify({ error: 'Application already approved' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Generate temporary password
    const tempPassword = generateTempPassword()

    // Create auth user
    const { data: authUser, error: authError } = await supabaseClient.auth.admin.createUser({
      email: application.email,
      password: tempPassword,
      email_confirm: true,
      user_metadata: {
        first_name: application.first_name,
        last_name: application.last_name,
        role: 'contractor',
      },
    })

    if (authError || !authUser.user) {
      console.error('Error creating auth user:', authError)
      return new Response(
        JSON.stringify({ error: 'Failed to create user account', details: authError?.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Create contractor entry
    // Note: slug is auto-generated by trigger unless customSlug is provided
    const { data: contractor, error: contractorError } = await supabaseClient
      .from('contractors')
      .insert({
        id: authUser.user.id,
        ...(customSlug && { slug: customSlug }), // Only set slug if custom slug provided
        slug_changes_count: 0,
      })
      .select()
      .single()

    if (contractorError) {
      console.error('Error creating contractor:', contractorError)
      // Cleanup: delete auth user
      await supabaseClient.auth.admin.deleteUser(authUser.user.id)
      return new Response(
        JSON.stringify({
          error: 'Failed to create contractor entry',
          details: contractorError.message,
          code: contractorError.code,
          hint: contractorError.hint
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Create contractor profile
    const { error: profileError } = await supabaseClient
      .from('contractor_profiles')
      .insert({
        contractor_id: contractor.id,
        bio: application.motivation ? application.motivation.substring(0, 500) : null, // Use first 500 chars of motivation if exists
        professional_title: application.profession,
        years_of_experience: application.years_of_experience,
        postal_codes: application.geographic_zones,
        is_visible: true,
        certifications_verified: false,
      })

    if (profileError) {
      console.error('Error creating profile:', profileError)
      // Don't fail the whole operation, just log it
      // The contractor can complete their profile later
    }

    // Create onboarding status
    const { error: onboardingError } = await supabaseClient
      .from('contractor_onboarding_status')
      .insert({
        contractor_id: contractor.id,
        account_created: true,
        schedule_configured: false,
        stripe_connect_completed: false,
        profile_completed: false,
      })

    if (onboardingError) {
      console.error('Error creating onboarding status:', onboardingError)
      // Don't fail the whole operation, just log it
    }

    // Link contractor_services from specialties
    if (application.specialties && application.specialties.length > 0) {
      // TODO: Create contractor_services entries based on specialties
      // This requires fetching service IDs from the services table
    }

    // Update application status
    const { error: updateError } = await supabaseClient
      .from('contractor_applications')
      .update({
        status: 'approved',
        approved_at: new Date().toISOString(),
        created_contractor_id: contractor.id,
        reviewed_at: new Date().toISOString(),
      })
      .eq('id', applicationId)

    if (updateError) {
      console.error('Error updating application:', updateError)
      return new Response(
        JSON.stringify({ error: 'Failed to update application status', details: updateError.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Send welcome email with credentials
    if (sendEmail) {
      const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')

      if (RESEND_API_KEY) {
        const emailResponse = await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${RESEND_API_KEY}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            from: 'Simone Paris <noreply@simone.paris>',
            to: [application.email],
            subject: '🎉 Bienvenue chez Simone Paris - Votre candidature est approuvée !',
            html: `
              <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <h1 style="color: #16a34a;">Félicitations ${application.first_name} !</h1>

                <p>Nous sommes ravis de vous informer que votre candidature a été acceptée. Bienvenue dans l'équipe Simone Paris ! 🎉</p>

                <div style="background-color: #f0fdf4; border-left: 4px solid #16a34a; padding: 16px; margin: 24px 0;">
                  <h2 style="margin-top: 0; color: #15803d;">Vos identifiants de connexion</h2>
                  <p style="margin: 8px 0;"><strong>Email :</strong> ${application.email}</p>
                  <p style="margin: 8px 0;"><strong>Mot de passe temporaire :</strong> <code style="background-color: #dcfce7; padding: 4px 8px; border-radius: 4px; font-size: 16px;">${tempPassword}</code></p>
                </div>

                <div style="background-color: #fef3c7; border-left: 4px solid #f59e0b; padding: 16px; margin: 24px 0;">
                  <p style="margin: 0; color: #92400e;">⚠️ <strong>Important :</strong> Vous devrez changer ce mot de passe lors de votre première connexion.</p>
                </div>

                <h2 style="color: #1e40af;">Prochaines étapes</h2>
                <ol style="line-height: 1.8;">
                  <li>Connectez-vous à votre espace prestataire : <a href="${Deno.env.get('NEXT_PUBLIC_SITE_URL') || 'http://localhost:3000'}/contractor/login" style="color: #2563eb;">Se connecter</a></li>
                  <li>Complétez votre processus d'onboarding (3 étapes) :
                    <ul>
                      <li>Configurez vos horaires de disponibilité</li>
                      <li>Connectez votre compte Stripe pour recevoir vos paiements</li>
                      <li>Finalisez votre profil public</li>
                    </ul>
                  </li>
                  <li>Commencez à recevoir des demandes de clients</li>
                </ol>

                <div style="background-color: #eff6ff; border-left: 4px solid #2563eb; padding: 16px; margin: 24px 0;">
                  <p style="margin: 0;"><strong>Votre lien de réservation personnalisé :</strong><br>
                  <a href="${Deno.env.get('NEXT_PUBLIC_SITE_URL') || 'http://localhost:3000'}/book/${contractor.slug}" style="color: #2563eb; font-size: 16px;">
                    simone.paris/book/${contractor.slug}
                  </a></p>
                  <p style="margin: 8px 0 0 0; font-size: 14px; color: #1e40af;">Vous pourrez le personnaliser depuis votre espace prestataire.</p>
                </div>

                <h2 style="color: #1e40af;">Besoin d'aide ?</h2>
                <p>Notre équipe est là pour vous accompagner. N'hésitez pas à nous contacter si vous avez des questions.</p>

                <p style="margin-top: 32px;">Bienvenue dans l'aventure !<br>
                <strong>L'équipe Simone Paris</strong></p>
              </div>
            `,
          }),
        })

        if (!emailResponse.ok) {
          console.error('Error sending email:', await emailResponse.text())
        }
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: 'Application approved and account created',
        contractorId: contractor.id,
        slug: contractor.slug,
        tempPassword: tempPassword, // Only for admin reference (not production)
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})

/**
 * Generate temporary password
 */
function generateTempPassword(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%'
  let password = ''
  for (let i = 0; i < 12; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return password
}
